### ISSUE TITLE
RPC agent for worker encountered error when reading incoming request from master

### ISSUE THREAD

**Issue by luisfredgs** [iHeartGraph/Euler#4]
Hello. I have the following error when using SAGE as a topologic encoder and LSTM to encode embeddings. I have taken a couple of hours seeking a solution but had no success. I can confirm it does not happen when I use GCN & LSTM. How to solve it? I guess the error is similar to #2.  However, following the suggestions in that thread has not helped me. Thank you very much.

`$ python run.py -t 5 -d 0.5 -e SAGE -r LSTM`

``Namespace(dataset='LANL', delta=0.5, encoder='SAGE', fpweight=0.5, hidden=32, impl='DETECT', load=False, lr=0.005, ngrus=1, nowrite=False, patience=5, rnn='LSTM', te_end=None, tests=5, threads=1, workers=8, zdim=16)
SAGE -> LSTM (DETECT)``

My environment:

- Python 3.8
- torch==1.11.0+cpu
- torch-geometric==2.1.0.post1
- joblib==1.1.0

The error:
```
Seconds read: 608401it [00:16, 37162.60it/s]                                                                                                                                                                                                
Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5884/5884 [00:16<00:00, 355.70it/s]
Seconds read: 608401it [00:16, 36779.50it/s]                                                                                                                                                                                                
Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7484/7484 [00:17<00:00, 430.15it/s]
Seconds read: 606601it [00:17, 34865.05it/s]                                                                                                                                                                                                
Embedding Test Data...

[W tensorpipe_agent.cpp:726] RPC agent for worker2 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker5 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker3 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker6 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker1 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker7 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker0 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
[W tensorpipe_agent.cpp:726] RPC agent for worker4 encountered error when reading incoming request from master: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
/home/euler/venvs/euler/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 6 leaked semlock objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/euler/venvs/euler/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 1 leaked folder objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Traceback (most recent call last):
  File "run.py", line 179, in <module>
    stats = [
  File "run.py", line 180, in <listcomp>
    run_all(
  File "/home/luisfred/Documents/Euler/src/lanl_experiments/spinup.py", line 529, in run_all
    mp.spawn(
  File "/home/luisfred/venvs/euler/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/luisfred/venvs/euler/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/luisfred/venvs/euler/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 8 terminated with signal SIGKILL
```

**Comment by zazyzaya** [comment]
Hi Luís, 

I am unfortunately unable to replicate this, even with those versions in a fresh environment. It's possible the issue is that your machine is running out of memory trying to load the entirety of the LANL data set into memory, as it only crashes during the testing phase? It would make sense to only crash on SAGE as well, since it has more parameters than GCN. I'm running this on a cluster with 500GB RAM so it's possible. 

To verify, does changing line 137 of `lanl_experiments/run.py` to 

    args.te_end = lanl.TIMES[20] # load less of the test set

fix this? This will make it so it only tests on 10% of the data.
